Dynamic Surrogates for Case Studies
gmlc-dispatches/dispatches pull request #163
Opened 2022-11-16 18:10 UTC by Xinhe-Chen

## Addresses issue:
#85 
## Summary/Motivation:
Surrogate automation workflow for different case studies. 
## Changes proposed in this PR:
- Make this new PR to solve some testing issues
- After creating this PR, close PR #98 

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md and COPYRIGHT.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-11-16 18:13 UTC, Xinhe-Chen commented
Open this new PR to replace PR #98.

2022-11-16 19:42 UTC, Xinhe-Chen commented
@lbianchi-lbl Hi Ludovico, I got some errors in the tests. To test my PR, I generated some data in the csv file and put them in the dispatches/tests/test_data folder in this branch. It seems that Github can't locate them correctly. 
If I want to read some data in my tests, what is the correct way that I should do?
![image](https://user-images.githubusercontent.com/95387042/202277874-03b50fad-da85-45db-9dc0-57294d635764.png)

2022-11-16 20:54 UTC, lbianchi-lbl commented
> @lbianchi-lbl Hi Ludovico, I got some errors in the tests. To test my PR, I generated some data in the csv file and put them in the dispatches/tests/test_data folder in this branch. It seems that Github can't locate them correctly. If I want to read some data in my tests, what is the correct way that I should do?

@Xinhe-Chen the files are not being located correctly because their paths are being constructed using `os.getcwd()`, which is fragile. Instead, I'd recommend the following:

- Create a directory `dispatches/workflow/train_market_surrogates/dynamic/tests/data` containing:
  - An empty `__init__.py` file
  - The data files currently stored in `dispatches/tests/test_data`
- This will result in the data files being accessible from the Python package named `dispatches.workflow.train_market_surrogates.dynamic.tests.data`
- Remove the now empty `dispatches/tests/test_data` directory
- In `setup.py`, under the `package_data` keyword, add an entry for the newly created `dispatches.workflow.train_market_surrogates.dynamic.tests.data`
  - This should be a list containing the data files (names only)
  - You should be able to use the existing entries as an example
- Rename `test_Simulation_Data.py` to `test_simulation_data.py`
- Inside the file, rename the fixtures `test_simulation_data` to `sample_simulation_data` and `test_input_data` to `sample_input_data`
  - Why: functions named `test_` have a special meaning for pytest (they are considered test functions). I don't think having fixtures named `test_xyz` would necessarily cause problems, but it's confusing and therefore best avoided
- In the fixtures, use the `importlib.resources.path()` pattern described here: https://github.com/gmlc-dispatches/dispatches/wiki/How-to:-get-the-absolute-path-to-a-data-file#for-data-files-located-in-a-python-package, e.g.:

```py
from pathlib import Path
try:
    # Pyton 3.8+
    from importlib import resources
except ImportError:
    # Python 3.7
    import importlib_resources as resources

import pytest


def _get_data_path(file_name: str, package: str = "dispatches.workflow.train_market_surrogates.dynamic.tests.data") -> Path:
    with resources.path(package, file_name) as p:
        return Path(p)

@pytest.fixture
def sample_simulation_data_path() -> Path:
    return _get_data_path("simdatatest.csv")
```

2022-11-18 00:29 UTC, lbianchi-lbl commented
@Xinhe-Chen if you want to speed up the CI runs so that only the tests for this PR run, you can temporarily change the command at https://github.com/gmlc-dispatches/dispatches/blob/fcdc05f68de83b7f9d23964de15a69a4476b2888/.github/workflows/checks.yml#L81 to e.g. `pytest -k train_market_surrogates` so that only the corresponding subset of tests are run.

The current test failures (`TypeError` about `str` being expected) can be resolved by calling `str()` before passing the `pathlib.Path` object where the `str` object is required (e.g. as far as I understand, `TrainNNSurrogates()`).

2022-11-18 15:34 UTC, Xinhe-Chen commented
@adowling2 @bknueven This PR is ready for review.

2022-11-18 16:32 UTC, lbianchi-lbl requested changes
I've looked at the files and left comments focusing mostly "low-hanging fruits" in terms of software engineering. @Xinhe-Chen Hopefully this doesn't come across as overly critical: this PR is large and likely represents even larger amounts of work from your side, and it's just a matter of keeping iterating on it a few times to make the code easier to deploy. 

A few more general comments:

- As of 9acf0179827348bcf6f300d092a29a6dfd436fb3, there are many `.jpg` files left in this branch. Unless there's a very strong reason to keep them there, they should be removed
- Some Python file names are not conforming to the `snake_case` naming convention (all lowercase letters separated by `_`) . Again, unless there's a strong reason to deviate from this, they should be modified (e.g. `Simulation_Data.py` should be `simulation_data.py`)
- There are several blocks of commented-out code left in the Python files. Pragmatically, this might make sense in some circumstances (e.g. quickly showcasing an alternative when creating a function would be more cumbersome), but we should make sure that any commented code that's not needed is removed

2022-11-18 16:32 UTC, lbianchi-lbl commented on dispatches/workflow/train_market_surrogates/dynamic/do_train_surrogates.py
> +from Time_Series_Clustering import TimeSeriesClustering
These import paths should be absolute (starting with `dispatches.workflow.train_market_surrogates`) or relative (starting with one or more `.`). For more information see e.g. https://realpython.com/absolute-vs-relative-python-imports/

2022-11-18 17:46 UTC, Xinhe-Chen commented on dispatches/workflow/train_market_surrogates/dynamic/Train_NN_Surrogates.py
> +sys.path.append(__this_file_dir__)
I will check all the imports. For most imports I did copy and paste.

2022-11-18 18:42 UTC, Xinhe-Chen commented
Thank you for the suggestions from @lbianchi-lbl . I reviewed again about the codes and I think I have some new things to do. 

- [ ] Optimize the codes that I read or save data. I should use better path tools like pathlib.Path. 
- [ ] Use jupyter notebooks to demonstrate how to train the surrogates instead of using a py script.
- [ ] Add some more tests to the util codes (codes that extract data from original data.)

2022-12-06 19:47 UTC, Xinhe-Chen commented
@adowling2 I have generated the min/max/median/max mileage/min mileage profiles. 
I think the improvement is limited. 
![FE_dispatch_95_5_mileage_2](https://user-images.githubusercontent.com/95387042/206007756-981ffb1c-c297-4055-8291-98ec37a4dcb0.jpg)

For some plots, the max captures the storage usage but 95% quantile does not. 
![FE_dispatch_95_5_mileage_14](https://user-images.githubusercontent.com/95387042/206008045-c50991c1-9030-41b5-9ad4-37aa7e449be4.jpg)

So I will say we will use the min/max/median as the sub-scenarios will be the best choice.

2022-12-06 19:48 UTC, Xinhe-Chen commented
@adowling2 I have generated the min/max/median/max mileage/min mileage profiles. 
I think the improvement is limited. 
![FE_dispatch_95_5_mileage_2](https://user-images.githubusercontent.com/95387042/206007756-981ffb1c-c297-4055-8291-98ec37a4dcb0.jpg)

For some plots, the max captures the storage usage but 95% quantile does not. 
![FE_dispatch_95_5_mileage_14](https://user-images.githubusercontent.com/95387042/206008045-c50991c1-9030-41b5-9ad4-37aa7e449be4.jpg)

So I will say we will use the min/max/median as the sub-scenarios will be the best choice.

2022-12-06 19:50 UTC, adowling2 commented
@Xinhe-Chen In the legend you should list the average capacity factor in ( ) for each line.

Please also see these tips on formatting figures: https://ndcbe.github.io/data-and-computing/notebooks/01/Publication-Quality-Figures.html

2022-12-06 20:49 UTC, Xinhe-Chen commented
@adowling2 Thanks for the comments. I have updated the plots. I made the plots larger sizes to show the legends. 

![FE_dispatch_95_5_mileage_2](https://user-images.githubusercontent.com/95387042/206019804-5405a028-a0d7-4bce-81a3-755c0ddbffb2.jpg)

![FE_dispatch_95_5_mileage_14](https://user-images.githubusercontent.com/95387042/206019750-136affdd-9ce4-46d2-8654-2ff0d40050e1.jpg)

2023-03-20 14:16 UTC, lbianchi-lbl commented on setup.py
> +        "tslearn>=0.5.2",
The `dynamic_sweep` data package need to be installed for it to work in CI:

```suggestion
        "dispatches-dynamic-sweep-data @ git+https://github.com/gmlc-dispatches/dynamic-sweep-data@main",
        "tslearn>=0.5.2",
```

2023-04-05 04:08 UTC, lbianchi-lbl approved these changes

2023-04-05 04:12 UTC, lbianchi-lbl commented
The only failing check is the test coverage, which is due to the fact that the two relatively large files `Time_Series_Clustering.py` and `Train_NN_Surrogates.py` are only partially covered by tests. I've created #195 to keep track of this.

2023-04-05 04:13 UTC, merged