updated FE models for design and pricetaker
gmlc-dispatches/dispatches pull request #209
Opened 2023-07-06 05:44 UTC by nareshsusarla

## Addresses issue:
This PR adds all FE case models including GDP design and multiperiod pricetaker for release

## Summary/Motivation:

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md and COPYRIGHT.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2023-07-06 18:36 UTC, adowling2 commented
@nareshsusarla Please add a README file in each (sub)folder of `dispatches/case_studies/fossil_case`. The README should include one sentence that summarizes the purpose and contents of each file.

2023-07-24 17:09 UTC, lbianchi-lbl requested changes
Note to self: revert the changes to `docs/conf.py` and `setup.py` (due to the fact that this branch originates from the `1.3_rel` branch, rather than `main`) before merging.

2023-07-27 14:43 UTC, esrawli approved these changes

2023-07-27 19:38 UTC, lbianchi-lbl commented on setup.py
> +    version="1.3.0rc0",
thanks for spotting this - it should be fixed now.

2023-07-27 19:39 UTC, merged